apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mygithub23/voting-app.git
    targetRevision: HEAD
    path: 
  destination: 
    server: https://kubernetes.default.svc
    namespace: app-vote

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
